version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      MIX_ENV: dev
      POSTGRES_HOST: db
      RABBITMQ_URI: amqp://guest:guest@rabbitmq:5672
    volumes:
      - ".:/app"
      - deps_cache:/app/deps
      - build_cache:/app/_build
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: localhost
      DATABASE_PASSWORD: postgres
      DATABASE_USERNAME: postgres
      DATABASE_DB: pokex_dev
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      PGUSER: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
volumes:
  deps_cache:
  build_cache:
